#define		LIGHTICON				1
#define		DARKICON				2
#define		PRODUCT_VER_MAJOR		2
#define		PRODUCT_VER_MINOR		1
#define		PRODUCT_VER_PATCH		0
#define		PRODUCT_VER_STR			TOSTRING(PRODUCT_VER_MAJOR) "." TOSTRING(PRODUCT_VER_MINOR) "." TOSTRING(PRODUCT_VER_PATCH) ".0"